title: Hammed Oyedele (@devhammed)
email: hey@hammed.dev
author: Hammed Oyedele
description: >-
  Innovative senior software engineer with 7+ years of experience in developing cutting-edge web and mobile applications. Recognized for technical leadership, mentoring capabilities, and expertise in JavaScript, PHP, and Dart. Passionate about fostering developer communities and driving technological advancements.
baseurl: ""
url: "https://hammed.dev"
permalink: /blog/:year/:month/:day/:title

theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
